DROP DATABASE IF EXISTS `todo`;
CREATE DATABASE `todo`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE 'todo';
GRANT ALL PRIVILEGES ON todo.* TO 'todo'@'localhost' IDENTIFIED BY 'todo'

WITH GRANT OPTION;
FLUSH PRIVILEGES;
